version: '3.4'
services:
  api:
    platform: "linux/amd64"
    build: backend/
    container_name: backend
    image: rmitsept/backend:latest
    ports:
      - "8080:8080"
  web:
    platform: "linux/amd64"
    build: frontend/
    container_name: frontend
    image: rmitsept/frontend:latest
    ports:
      - "3000:3000"
    environment:
      API_URL: "http://api:8080"
    depends_on:
      - api
